schema_version = "1.0.0"
blender_version_min = "4.2.0"
version = "0.3.2"
id = "image_editor_tools"
name = "Image Editor Master [图像超级工具]"
tagline = "Super Image Toolbox (color, filters, texture optimization)"
license = ["SPDX:GPL-3.0-or-later"]
maintainer = "RARA"
type = "add-on"
website = "https://space.bilibili.com/27284213"
copyright = ["2026 RARA"]
tags = ["Paint", "Compositing", "Material"]