# gen_lang_packs.py
# 生成 ja_JP / fr_FR / ru_RU / de_DE 语言包。
# 读取 en_US.py 的全部词条作为权威键集；主表 M 提供 ja/fr/ru/de 翻译，
# 未覆盖的键自动回退英文（保证每个语言包完整、无中文残留）。
# 用法: python gen_lang_packs.py
import os, json

HERE = os.path.dirname(os.path.abspath(__file__))
TRANS_DIR = os.path.join(HERE, "..", "translation")

ns = {}
with open(os.path.join(TRANS_DIR, "en_US.py"), encoding="utf-8") as f:
    exec(f.read(), ns)
EN = ns["data"]

# 主翻译表: 中文 -> (ja, fr, ru, de)。未列出的键回退英文。
M = {
    # —— 面板/分类/工具名 ——
    "图像编辑工具集": ("画像エディタツール", "Outils d'édition d'image", "Инструменты редактора изображений", "Bildbearbeitungswerkzeuge"),
    "工具面板": ("ツールパネル", "Panneau d'outils", "Панель инструментов", "Werkzeugleiste"),
    "工具": ("ツール", "Outils", "Инструменты", "Werkzeuge"),
    "色调调整": ("色調補正", "Réglage des couleurs", "Коррекция цвета", "Farbanpassung"),
    "滤镜效果": ("フィルター効果", "Effets de filtre", "Фильтры", "Filtereffekte"),
    "贴图处理": ("テクスチャ処理", "Traitement de texture", "Обработка текстур", "Texturverarbeitung"),
    "几何变形": ("ジオメトリ変形", "Déformation géométrique", "Геометрическая деформация", "Geometrische Verzerrung"),
    "基础调色器": ("基本カラー", "Couleur de base", "Базовый цвет", "Grundfarbe"),
    "通道混合器": ("チャンネルミキサー", "Mélangeur de canaux", "Микшер каналов", "Kanalmischer"),
    "颜色混色器": ("カラーミキサー", "Mélangeur de couleurs", "Микшер цветов", "Farbmischer"),
    "色阶": ("レベル", "Niveaux", "Уровни", "Tonwerte"),
    "色彩迁徙": ("カラー転送", "Transfert de couleur", "Перенос цвета", "Farbübertragung"),
    "色调分离": ("ポスタリゼーション", "Postérisation", "Постеризация", "Posterisieren"),
    "色深优化": ("ビット深度最適化", "Optimisation de profondeur", "Оптимизация глубины", "Bittiefe optimieren"),
    "反相": ("反転", "Inverser", "Инвертировать", "Invertieren"),
    "模糊": ("ぼかし", "Flou", "Размытие", "Weichzeichnen"),
    "方向模糊": ("方向ぼかし", "Flou directionnel", "Направленное размытие", "Richtungsunschärfe"),
    "高反差保留": ("ハイパス", "Passe-haut", "Цветовой контраст", "Hochpass"),
    "USM锐化": ("USMシャープ", "Netteté USM", "Нерезкая маска", "USM-Schärfen"),
    "噪点": ("ノイズ", "Bruit", "Шум", "Rauschen"),
    "边缘检测": ("エッジ検出", "Détection de contours", "Выделение краёв", "Kantenerkennung"),
    "位移": ("オフセット", "Décalage", "Смещение", "Versatz"),
    "马赛克": ("モザイク", "Mosaïque", "Мозаика", "Mosaik"),
    "晶格化": ("結晶化", "Cristalliser", "Кристаллизация", "Kristallisieren"),
    "浮雕": ("エンボス", "Repoussage", "Тиснение", "Relief"),
    "减少杂色": ("ノイズ除去", "Réduction du bruit", "Шумоподавление", "Entrauschen"),
    "色彩半调": ("ハーフトーン", "Demi-teinte", "Полутон", "Halbton"),
    "法线生成": ("ノーマル生成", "Génération de normale", "Карта нормалей", "Normale erzeugen"),
    "法线还原高度": ("ノーマルから高さ", "Hauteur depuis normale", "Высота из нормали", "Höhe aus Normale"),
    "贴图无缝化": ("シームレス化", "Rendre sans couture", "Бесшовность", "Nahtlos machen"),
    "黑底抠图": ("アルファ再構築", "Reconstruire l'alpha", "Восстановить альфу", "Alpha rekonstruieren"),
    "图像合成": ("合成", "Composition", "Композиция", "Komposition"),
    "均匀光影": ("均一ライティング", "Éclairage uniforme", "Равномерный свет", "Gleichmäßige Beleuchtung"),
    "高度→AO": ("高さ→AO", "Hauteur→AO", "Высота→AO", "Höhe→AO"),
    "曲率图": ("曲率", "Courbure", "Кривизна", "Krümmung"),
    "置入图像": ("画像配置", "Placer une image", "Вставить изображение", "Bild platzieren"),
    "置入文字": ("テキスト配置", "Placer un texte", "Вставить текст", "Text platzieren"),
    "切分图像": ("画像分割", "Découper l'image", "Разрезать изображение", "Bild teilen"),
    "通道修改": ("チャンネル編集", "Modifier les canaux", "Изменить каналы", "Kanäle ändern"),
    "颜色替换": ("色の置換", "Remplacer une couleur", "Замена цвета", "Farbe ersetzen"),
    "法线转换": ("ノーマル変換", "Convertir la normale", "Конвертация нормалей", "Normale konvertieren"),
    "在内部图像编辑器中编辑": ("内部画像エディタで編集", "Éditer dans l'éditeur interne", "Править во внутреннем редакторе", "Im internen Editor bearbeiten"),
    "贝塞尔扭曲": ("メッシュ変形", "Déformation par maillage", "Деформация сеткой", "Netzverzerrung"),
    "透视形变": ("透視変形", "Déformation de perspective", "Перспективная деформация", "Perspektivverzerrung"),
    "自由裁切": ("自由切り抜き", "Recadrage libre", "Свободная обрезка", "Freies Zuschneiden"),
    "取消": ("キャンセル", "Annuler", "Отмена", "Abbrechen"),
    "应用": ("適用", "Appliquer", "Применить", "Anwenden"),
    "另存": ("別名保存", "Enregistrer sous", "Сохранить как", "Speichern unter"),
    "保存": ("保存", "Enregistrer", "Сохранить", "Speichern"),
    "启动编辑工具": ("編集ツールを起動", "Lancer l'outil d'édition", "Запустить инструмент", "Bearbeitungswerkzeug starten"),
    "在内部编辑器打开图像": ("内部エディタで画像を開く", "Ouvrir dans l'éditeur interne", "Открыть во внутреннем редакторе", "Im internen Editor öffnen"),
    "调色": ("カラー調整", "Ajuster les couleurs", "Цветокоррекция", "Farbe anpassen"),
    "混色器": ("ミキサー", "Mélangeur", "Микшер", "Mischer"),

    # —— GPU/CPU 双引擎 ——
    "引擎": ("エンジン", "Moteur", "Движок", "Engine"),
    "模糊引擎": ("ぼかしエンジン", "Moteur de flou", "Движок размытия", "Weichzeichner-Engine"),
    "模糊强度": ("ぼかし強度", "Intensité du flou", "Сила размытия", "Weichzeichnungsstärke"),
    "模糊类型": ("ぼかしタイプ", "Type de flou", "Тип размытия", "Weichzeichnungstyp"),
    "方向角度": ("方向角度", "Angle directionnel", "Угол направления", "Richtungswinkel"),

    # —— 属性名 ——
    "曝光度": ("露出", "Exposition", "Экспозиция", "Belichtung"),
    "曝光": ("露出", "Exposition", "Экспозиция", "Belichtung"),
    "偏移": ("オフセット", "Décalage", "Смещение", "Versatz"),
    "灰度系数": ("ガンマ", "Gamma", "Гамма", "Gamma"),
    "青色-红色": ("シアン-レッド", "Cyan-Rouge", "Голубой-Красный", "Cyan-Rot"),
    "洋红-绿色": ("マゼンタ-グリーン", "Magenta-Vert", "Пурпурный-Зелёный", "Magenta-Grün"),
    "黄色-蓝色": ("イエロー-ブルー", "Jaune-Bleu", "Жёлтый-Синий", "Gelb-Blau"),
    "保持明度": ("輝度を保持", "Conserver la luminosité", "Сохранить яркость", "Helligkeit beibehalten"),
    "保持原始明度": ("元の輝度を保持", "Conserver la luminosité d'origine", "Сохранить исходную яркость", "Originalhelligkeit beibehalten"),
    "色相": ("色相", "Teinte", "Тон", "Farbton"),
    "饱和度": ("彩度", "Saturation", "Насыщенность", "Sättigung"),
    "明度": ("明度", "Luminosité", "Светлота", "Helligkeit"),
    "自然饱和度": ("自然な彩度", "Vibrance", "Сочность", "Dynamik"),
    "对比度": ("コントラスト", "Contraste", "Контраст", "Kontrast"),
    "R 通道": ("Rチャンネル", "Canal rouge", "Канал R", "Rot-Kanal"),
    "G 通道": ("Gチャンネル", "Canal vert", "Канал G", "Grün-Kanal"),
    "B 通道": ("Bチャンネル", "Canal bleu", "Канал B", "Blau-Kanal"),
    "输入黑点": ("入力黒点", "Point noir d'entrée", "Входная чёрная точка", "Eingang Schwarzpunkt"),
    "输入白点": ("入力白点", "Point blanc d'entrée", "Входная белая точка", "Eingang Weißpunkt"),
    "中间调": ("中間調", "Tons moyens", "Средние тона", "Mitteltöne"),
    "输出黑点": ("出力黒点", "Point noir de sortie", "Выходная чёрная точка", "Ausgang Schwarzpunkt"),
    "输出白点": ("出力白点", "Point blanc de sortie", "Выходная белая точка", "Ausgang Weißpunkt"),
    "单色": ("モノクロ", "Monochrome", "Монохром", "Monochrom"),
    "模糊半径": ("ぼかし半径", "Rayon du flou", "Радиус размытия", "Weichzeichnungsradius"),
    "模糊模式": ("ぼかしモード", "Mode de flou", "Режим размытия", "Weichzeichnungsmodus"),
    "模糊角度": ("ぼかし角度", "Angle du flou", "Угол размытия", "Weichzeichnungswinkel"),
    "边界填充": ("境界の埋め方", "Remplissage des bords", "Заполнение границ", "Randfüllung"),
    "快速模糊": ("高速ぼかし", "Flou rapide", "Быстрое размытие", "Schnelles Weichzeichnen"),
    "格子大小": ("セルサイズ", "Taille de cellule", "Размер ячейки", "Zellengröße"),
    "细节强度": ("ディテール強度", "Intensité des détails", "Сила деталей", "Detailstärke"),
    "全局羽化": ("全体フェザー", "Adoucissement global", "Глобальное растушёвывание", "Globale Weichzeichnung"),
    "网点半径": ("ドット半径", "Rayon de point", "Радиус точки", "Punktradius"),
    "抗锯齿": ("アンチエイリアス", "Anticrénelage", "Сглаживание", "Kantenglättung"),
    "强度": ("強度", "Intensité", "Сила", "Stärke"),
    "保留细节": ("ディテール保持", "Préserver les détails", "Сохранить детали", "Details erhalten"),
    "模式": ("モード", "Mode", "Режим", "Modus"),
    "水平": ("水平", "Horizontal", "Горизонталь", "Horizontal"),
    "垂直": ("垂直", "Vertical", "Вертикаль", "Vertikal"),
    "前景图": ("前景画像", "Image de premier plan", "Изображение переднего плана", "Vordergrundbild"),
    "不透明度": ("不透明度", "Opacité", "Непрозрачность", "Deckkraft"),
    "色阶数": ("レベル数", "Nombre de niveaux", "Число уровней", "Anzahl Stufen"),
    "参考图": ("参照画像", "Image de référence", "Эталонное изображение", "Referenzbild"),
    "混合": ("ブレンド", "Mélange", "Смешивание", "Mischen"),
    "位深": ("ビット深度", "Profondeur de bits", "Битовая глубина", "Bittiefe"),
    "噪点类型": ("ノイズタイプ", "Type de bruit", "Тип шума", "Rauschtyp"),
    "锐化强度": ("シャープ強度", "Intensité de netteté", "Сила резкости", "Schärfestärke"),
    "反转绿色通道": ("緑チャンネル反転", "Inverser le canal vert", "Инвертировать зелёный канал", "Grün-Kanal invertieren"),
    "方法": ("方法", "Méthode", "Метод", "Methode"),
    "样式": ("スタイル", "Style", "Стиль", "Stil"),
    "混合宽度": ("ブレンド幅", "Largeur de mélange", "Ширина смешивания", "Mischbreite"),
    "重叠宽度": ("重なり幅", "Largeur de recouvrement", "Ширина перекрытия", "Überlappungsbreite"),
    "梯度惩罚": ("勾配ペナルティ", "Pénalité de gradient", "Штраф градиента", "Gradientenstrafe"),
    "晶格数量": ("セル数", "Nombre de cellules", "Число ячеек", "Zellenanzahl"),
    "快速模式": ("高速モード", "Mode rapide", "Быстрый режим", "Schnellmodus"),
    "高反差半径": ("ハイパス半径", "Rayon passe-haut", "Радиус контраста", "Hochpass-Radius"),
    "基色模式": ("ベースカラーモード", "Mode couleur de base", "Режим базового цвета", "Grundfarbmodus"),
    "基色": ("ベースカラー", "Couleur de base", "Базовый цвет", "Grundfarbe"),
    "替换范围": ("置換範囲", "Plage de remplacement", "Диапазон замены", "Ersetzungsbereich"),
    "混合强度": ("ブレンド強度", "Intensité du mélange", "Сила смешивания", "Mischstärke"),
    "转换模式": ("変換モード", "Mode de conversion", "Режим конвертации", "Konvertierungsmodus"),
    "自动归一化": ("自動正規化", "Normalisation auto", "Авто-нормализация", "Auto-Normalisierung"),
    "半径": ("半径", "Rayon", "Радиус", "Radius"),
    "采样数": ("サンプル数", "Échantillons", "Сэмплы", "Abtastungen"),
    "输入类型": ("入力タイプ", "Type d'entrée", "Тип ввода", "Eingabetyp"),
    "细节": ("ディテール", "Détail", "Детали", "Detail"),
    "翻转 G 通道": ("Gチャンネル反転", "Inverser le canal G", "Перевернуть канал G", "G-Kanal umkehren"),
    "角度": ("角度", "Angle", "Угол", "Winkel"),
    "来源": ("ソース", "Source", "Источник", "Quelle"),
    "彩色噪点": ("カラーノイズ", "Bruit couleur", "Цветной шум", "Farbrauschen"),
    "随机种子": ("乱数シード", "Graine aléatoire", "Случайное зерно", "Zufallswert"),
    "影响 Alpha": ("アルファに影響", "Affecter l'alpha", "Влиять на альфу", "Alpha beeinflussen"),
    "预览": ("プレビュー", "Aperçu", "Предпросмотр", "Vorschau"),
    "文字": ("テキスト", "Texte", "Текст", "Text"),
    "字体": ("フォント", "Police", "Шрифт", "Schriftart"),
    "字号": ("文字サイズ", "Taille de police", "Размер шрифта", "Schriftgröße"),
    "字间距": ("文字間隔", "Espacement", "Межбуквенный интервал", "Zeichenabstand"),
    "倾斜": ("斜体", "Italique", "Курсив", "Kursiv"),
    "纵向": ("縦", "Colonnes", "Столбцы", "Spalten"),
    "横向": ("横", "Lignes", "Строки", "Zeilen"),
    "文字内容": ("テキスト内容", "Contenu du texte", "Содержание текста", "Textinhalt"),
    "字体文件": ("フォントファイル", "Fichier de police", "Файл шрифта", "Schriftdatei"),
    "文字颜色": ("文字色", "Couleur du texte", "Цвет текста", "Textfarbe"),
    "倾斜角度": ("傾斜角", "Angle d'italique", "Угол наклона", "Kursivwinkel"),
    "出血": ("裁ち落とし", "Fond perdu", "Вылет", "Anschnitt"),
    "纵向分割数": ("縦分割数", "Divisions verticales", "Вертикальные деления", "Vertikale Teilungen"),
    "横向分割数": ("横分割数", "Divisions horizontales", "Горизонтальные деления", "Horizontale Teilungen"),
    "节点编辑器右键菜单": ("ノードエディタ右クリックメニュー", "Menu contextuel de l'éditeur de nœuds", "Контекстное меню редактора узлов", "Node-Editor-Kontextmenü"),
    "预览通道": ("プレビューチャンネル", "Canal d'aperçu", "Канал предпросмотра", "Vorschaukanal"),
    "A 源": ("Aソース", "Source A", "Источник A", "Quelle A"),
    "B 源": ("Bソース", "Source B", "Источник B", "Quelle B"),
    "G 源": ("Gソース", "Source G", "Источник G", "Quelle G"),
    "R 源": ("Rソース", "Source R", "Источник R", "Quelle R"),
    "图 A": ("画像A", "Image A", "Изображение A", "Bild A"),
    "图 B": ("画像B", "Image B", "Изображение B", "Bild B"),
    "图 G": ("画像G", "Image G", "Изображение G", "Bild G"),
    "图 R": ("画像R", "Image R", "Изображение R", "Bild R"),
    "网点半径": ("ドット半径", "Rayon de point", "Радиус точки", "Punktradius"),

    # —— 枚举项 ——
    "盒式模糊": ("ボックスぼかし", "Flou de boîte", "Коробчатое размытие", "Boxweichzeichner"),
    "高斯模糊": ("ガウスぼかし", "Flou gaussien", "Размытие по Гауссу", "Gauß-Weichzeichner"),
    "堆叠盒式": ("スタックボックス", "Boîte empilée", "Стопка коробок", "Gestapelte Box"),
    "Kawase 模糊": ("Kawaseぼかし", "Flou Kawase", "Размытие Kawase", "Kawase-Weichzeichner"),
    "边缘重复": ("エッジ繰り返し", "Répéter les bords", "Повтор краёв", "Kanten wiederholen"),
    "循环平铺": ("ループタイル", "Bouclage", "Циклическая укладка", "Kacheln"),
    "智能填充": ("スマート塗りつぶし", "Remplissage intelligent", "Умное заполнение", "Intelligente Füllung"),
    "折回": ("折り返し", "Enroulement", "Заворот", "Umbruch"),
    "透明": ("透明", "Transparent", "Прозрачный", "Transparent"),
    "高斯噪点": ("ガウスノイズ", "Bruit gaussien", "Гауссов шум", "Gauß-Rauschen"),
    "椒盐噪点": ("ごま塩ノイズ", "Bruit sel et poivre", "Шум соль-перец", "Salz-und-Pfeffer-Rauschen"),
    "基础混合": ("基本ブレンド", "Mélange de base", "Базовое смешивание", "Basismischung"),
    "高级缝合": ("高度なシーム", "Couture avancée", "Продвинутый шов", "Erweiterte Naht"),
    "去条带": ("バンディング除去", "Anti-bandes", "Устранение полос", "Entbänderung"),
    "仿色": ("ディザリング", "Tramage", "Дизеринг", "Dithering"),
    "正常": ("通常", "Normal", "Обычный", "Normal"),
    "变暗": ("比較(暗)", "Obscurcir", "Затемнение", "Abdunkeln"),
    "正片叠底": ("乗算", "Produit", "Умножение", "Multiplizieren"),
    "颜色加深": ("焼き込みカラー", "Densité couleur +", "Затемнение основы", "Farbig nachbelichten"),
    "变亮": ("比較(明)", "Éclaircir", "Осветление", "Aufhellen"),
    "滤色": ("スクリーン", "Superposition d'écran", "Экран", "Negativ multiplizieren"),
    "颜色减淡": ("覆い焼きカラー", "Densité couleur -", "Осветление основы", "Farbig abwedeln"),
    "线性减淡": ("覆い焼き(リニア)", "Densité linéaire -", "Линейный осветлитель", "Linear abwedeln"),
    "叠加": ("オーバーレイ", "Incrustation", "Перекрытие", "Ineinanderkopieren"),
    "柔光": ("ソフトライト", "Lumière douce", "Мягкий свет", "Weiches Licht"),
    "线性光": ("リニアライト", "Lumière linéaire", "Линейный свет", "Lineares Licht"),
    "差值": ("差の絶対値", "Différence", "Разница", "Differenz"),
    "排除": ("除外", "Exclusion", "Исключение", "Ausschluss"),
    "减去": ("減算", "Soustraction", "Вычитание", "Subtrahieren"),
    "划分": ("除算", "Division", "Деление", "Dividieren"),
    "平均色": ("平均色", "Couleur moyenne", "Средний цвет", "Durchschnittsfarbe"),
    "强模糊": ("強いぼかし", "Flou intense", "Сильное размытие", "Starke Unschärfe"),
    "自定义": ("カスタム", "Personnalisé", "Произвольный", "Benutzerdefiniert"),
    "高度图": ("ハイトマップ", "Carte de hauteur", "Карта высот", "Höhenkarte"),
    "法线贴图": ("ノーマルマップ", "Carte de normales", "Карта нормалей", "Normalkarte"),

    # —— 颜色 ——
    "红色": ("赤", "Rouge", "Красный", "Rot"),
    "橙色": ("オレンジ", "Orange", "Оранжевый", "Orange"),
    "黄色": ("黄", "Jaune", "Жёлтый", "Gelb"),
    "绿色": ("緑", "Vert", "Зелёный", "Grün"),
    "浅绿": ("黄緑", "Vert clair", "Светло-зелёный", "Hellgrün"),
    "蓝色": ("青", "Bleu", "Синий", "Blau"),
    "紫色": ("紫", "Violet", "Фиолетовый", "Lila"),
    "洋红": ("マゼンタ", "Magenta", "Пурпурный", "Magenta"),
    "输出R": ("出力R", "Sortie R", "Выход R", "Ausgang R"),
    "输出G": ("出力G", "Sortie G", "Выход G", "Ausgang G"),
    "输出B": ("出力B", "Sortie B", "Выход B", "Ausgang B"),
    "常数": ("定数", "Constante", "Константа", "Konstante"),

    # —— 面板标签 ——
    "色彩平衡": ("カラーバランス", "Balance des couleurs", "Цветовой баланс", "Farbbalance"),
    "色相 / 饱和度": ("色相 / 彩度", "Teinte / Saturation", "Тон / Насыщенность", "Farbton / Sättigung"),
    "增强": ("強調", "Amélioration", "Усиление", "Verbesserung"),
    "输入色阶": ("入力レベル", "Niveaux d'entrée", "Входные уровни", "Eingabe-Tonwerte"),
    "输出色阶": ("出力レベル", "Niveaux de sortie", "Выходные уровни", "Ausgabe-Tonwerte"),
    "黑点": ("黒点", "Point noir", "Чёрная точка", "Schwarzpunkt"),
    "白点": ("白点", "Point blanc", "Белая точка", "Weißpunkt"),
    "请输入文字内容": ("テキストを入力してください", "Veuillez saisir le texte", "Введите текст", "Bitte Text eingeben"),
    "请选择一幅前景图": ("前景画像を選択してください", "Sélectionnez une image de premier plan", "Выберите изображение переднего плана", "Bitte Vordergrundbild wählen"),
    "请选择一幅参考图": ("参照画像を選択してください", "Sélectionnez une image de référence", "Выберите эталонное изображение", "Bitte Referenzbild wählen"),
    "面板分类（默认展开）": ("パネル分類（既定で展開）", "Catégories de panneau (déployées par défaut)", "Категории панели (развёрнуты по умолчанию)", "Panel-Kategorien (standardmäßig erweitert)"),

    # —— HUD/状态 短词 ——
    "原图 | 预览图": ("元画像 | プレビュー", "Original | Aperçu", "Оригинал | Предпросмотр", "Original | Vorschau"),
    "预览图 | 原图": ("プレビュー | 元画像", "Aperçu | Original", "Предпросмотр | Оригинал", "Vorschau | Original"),
    "仅原图": ("元画像のみ", "Original seul", "Только оригинал", "Nur Original"),
    "仅预览图": ("プレビューのみ", "Aperçu seul", "Только предпросмотр", "Nur Vorschau"),
    "拉伸": ("ストレッチ", "Étirer", "Растянуть", "Strecken"),
    "重复": ("繰り返し", "Répéter", "Повтор", "Wiederholen"),
    "白底": ("白背景", "Fond blanc", "Белый фон", "Weißer Hintergrund"),
    "黑底": ("黒背景", "Fond noir", "Чёрный фон", "Schwarzer Hintergrund"),
    "未在选中节点中找到任何图像对象": ("選択ノードに画像が見つかりません", "Aucune image trouvée dans les nœuds sélectionnés", "В выбранных узлах не найдено изображений", "Kein Bild in ausgewählten Nodes gefunden"),
    "剪贴板中无有效图像": ("クリップボードに有効な画像がありません", "Aucune image valide dans le presse-papiers", "В буфере обмена нет изображения", "Kein gültiges Bild in der Zwischenablage"),
    "请在图像编辑器中打开一张图片": ("画像エディタで画像を開いてください", "Ouvrez une image dans l'éditeur d'image", "Откройте изображение в редакторе", "Bitte ein Bild im Bildeditor öffnen"),
}

# —— 补充: 长描述/枚举描述/状态/HUD (占位符与按键名保持原样) ——
M2 = {
    "启动图像编辑模态": ("画像編集モーダルを起動", "Lancer le mode d'édition d'image", "Запустить режим редактирования изображения", "Bildbearbeitungsmodus starten"),
    "取消当前工具操作": ("現在のツール操作をキャンセル", "Annuler l'opération en cours", "Отменить текущую операцию", "Aktuelle Werkzeugaktion abbrechen"),
    "以当前参数编辑原图": ("現在のパラメータで元画像を編集", "Éditer l'image avec les paramètres actuels", "Править оригинал с текущими параметрами", "Original mit aktuellen Parametern bearbeiten"),
    "复制原图后以当前参数对副本进行编辑": ("元画像を複製して現在のパラメータで編集", "Dupliquer et éditer avec les paramètres actuels", "Дублировать и править с текущими параметрами", "Original duplizieren und mit aktuellen Parametern bearbeiten"),
    "常量(R)": ("定数(R)", "Constante (R)", "Константа (R)", "Konstante (R)"),
    "常量(G)": ("定数(G)", "Constante (G)", "Константа (G)", "Konstante (G)"),
    "常量(B)": ("定数(B)", "Constante (B)", "Константа (B)", "Konstante (B)"),
    "输出灰度图": ("グレースケール出力", "Sortie en niveaux de gris", "Вывод в градациях серого", "Graustufen ausgeben"),
    "控制保留细节的尺度，值越大保留更大尺度的结构": ("ディテール保持のスケールを制御。値が大きいほど大きな構造を保持", "Contrôle l'échelle des détails ; valeur élevée = grandes structures préservées", "Управляет масштабом деталей; больше значение — крупнее сохраняемые структуры", "Steuert die Detailskala; höhere Werte erhalten größere Strukturen"),
    "高频细节的加强倍率": ("高周波ディテールの強調倍率", "Multiplicateur d'accentuation des détails fins", "Множитель усиления мелких деталей", "Verstärkungsfaktor für Hochfrequenzdetails"),
    "模糊强度 (0-100)": ("ぼかし強度 (0-100)", "Intensité du flou (0-100)", "Сила размытия (0-100)", "Weichzeichnungsstärke (0-100)"),
    "模糊算法": ("ぼかしアルゴリズム", "Algorithme de flou", "Алгоритм размытия", "Weichzeichnungsalgorithmus"),
    "方向模糊的角度 (-180~180, 0=水平)": ("方向ぼかしの角度 (-180~180, 0=水平)", "Angle du flou directionnel (-180~180, 0=horizontal)", "Угол направленного размытия (-180~180, 0=горизонталь)", "Winkel der Richtungsunschärfe (-180~180, 0=horizontal)"),
    "图像边缘外像素的填充方式": ("画像端外ピクセルの埋め方", "Mode de remplissage hors limites", "Заполнение пикселей вне границ", "Füllmodus für Pixel außerhalb des Bildes"),
    "先缩到 1/2 做模糊再还原，大幅加速": ("1/2に縮小してぼかし後に復元、大幅高速化", "Réduit à 1/2 pour flouter puis restaure, bien plus rapide", "Уменьшить до 1/2, размыть и восстановить — намного быстрее", "Auf 1/2 verkleinern, weichzeichnen, wiederherstellen — viel schneller"),
    "像素块尺寸": ("ピクセルブロックサイズ", "Taille de bloc de pixels", "Размер блока пикселей", "Pixelblockgröße"),
    "最大网点半径": ("最大ドット半径", "Rayon de point maximal", "Макс. радиус точки", "Maximaler Punktradius"),
    "网屏角度": ("スクリーン角度", "Angle de trame", "Угол растра", "Rasterwinkel"),
    "边缘平滑过渡的像素宽度，0为无抗锯齿": ("エッジ平滑化のピクセル幅、0でアンチエイリアスなし", "Largeur d'adoucissement des bords ; 0 = pas d'anticrénelage", "Ширина сглаживания краёв; 0 = без сглаживания", "Pixelbreite der Kantenglättung; 0 = keine Glättung"),
    "白底黑点 ↔ 黑底白点": ("白地に黒点 ↔ 黒地に白点", "Fond blanc points noirs ↔ Fond noir points blancs", "Белый фон чёрные точки ↔ Чёрный фон белые точки", "Weißer Grund schwarze Punkte ↔ Schwarzer Grund weiße Punkte"),
    "降噪强度": ("ノイズ除去強度", "Intensité du débruitage", "Сила шумоподавления", "Entrauschungsstärke"),
    "边缘保护程度": ("エッジ保護レベル", "Niveau de préservation des bords", "Степень защиты краёв", "Kantenerhaltungsgrad"),
    "浮雕凹凸强度": ("エンボスの凹凸強度", "Intensité du relief", "Сила рельефа", "Reliefstärke"),
    "越界像素处理方式": ("範囲外ピクセルの処理方法", "Traitement des pixels hors limites", "Обработка пикселей вне границ", "Behandlung von Pixeln außerhalb des Bereichs"),
    "水平位移比例": ("水平オフセット比率", "Ratio de décalage horizontal", "Доля горизонтального смещения", "Horizontales Versatzverhältnis"),
    "垂直位移比例": ("垂直オフセット比率", "Ratio de décalage vertical", "Доля вертикального смещения", "Vertikales Versatzverhältnis"),
    "用于叠加合成的前景图像": ("合成用の前景画像", "Image de premier plan pour la composition", "Изображение переднего плана для композиции", "Vordergrundbild für die Komposition"),
    "混合模式": ("ブレンドモード", "Mode de fusion", "Режим наложения", "Mischmodus"),
    "前景不透明度": ("前景の不透明度", "Opacité du premier plan", "Непрозрачность переднего плана", "Vordergrund-Deckkraft"),
    "量化层级数量": ("量子化レベル数", "Nombre de niveaux de quantification", "Число уровней квантования", "Anzahl Quantisierungsstufen"),
    "用于迁移色彩风格的参考图像": ("色スタイル転送用の参照画像", "Image de référence pour le transfert de style colorimétrique", "Эталон для переноса цветового стиля", "Referenzbild für Farbstilübertragung"),
    "0=原图，1=完全迁移": ("0=元画像, 1=完全転送", "0=original, 1=transfert complet", "0=оригинал, 1=полный перенос", "0=Original, 1=vollständig übertragen"),
    "色深处理模式": ("ビット深度処理モード", "Mode de traitement de profondeur de bits", "Режим обработки битовой глубины", "Bittiefen-Verarbeitungsmodus"),
    "去条带=源位深(越低越激进) / 仿色=目标位深": ("バンディング除去=元深度(低いほど積極的) / ディザ=目標深度", "Anti-bandes=profondeur source (bas=agressif) / Tramage=profondeur cible", "Устранение полос=исходная глубина (ниже=агрессивнее) / Дизеринг=целевая глубина", "Entbänderung=Quelltiefe (niedriger=aggressiver) / Dithering=Zieltiefe"),
    "噪点生成算法": ("ノイズ生成アルゴリズム", "Algorithme de génération de bruit", "Алгоритм генерации шума", "Rauschgenerierungsalgorithmus"),
    "噪点强度（高斯=标准差，椒盐=密度）": ("ノイズ強度(ガウス=標準偏差, ごま塩=密度)", "Intensité du bruit (Gaussien=écart-type, Sel et Poivre=densité)", "Сила шума (Гаусс=ст.откл., соль-перец=плотность)", "Rauschstärke (Gauß=Standardabw., Salz und Pfeffer=Dichte)"),
    "噪点强度": ("ノイズ強度", "Intensité du bruit", "Сила шума", "Rauschintensität"),
    "RGB 通道独立加噪，产生彩色噪点效果": ("RGB各チャンネルに独立ノイズでカラーノイズ効果", "Bruit indépendant par canal RVB pour un effet de bruit couleur", "Независимый шум по каналам RGB для цветного шума", "Unabhängiges Rauschen pro RGB-Kanal für Farbrauschen"),
    "固定随机种子以获得可复现的噪点图案 (0=每次随机)": ("乱数シードを固定して再現可能なノイズパターン (0=毎回ランダム)", "Graine fixe pour un motif de bruit reproductible (0=aléatoire à chaque fois)", "Фикс. зерно для воспроизводимого шума (0=случайно каждый раз)", "Fester Zufallswert für reproduzierbares Rauschen (0=jedes Mal zufällig)"),
    "噪点是否同时影响 Alpha 通道": ("ノイズをアルファチャンネルにも適用するか", "Le bruit affecte-t-il aussi le canal alpha", "Влияет ли шум на альфа-канал", "Ob Rauschen auch den Alphakanal betrifft"),
    "USM 底层模糊的 σ 值": ("USM下層ぼかしのσ値", "Valeur sigma du flou USM sous-jacent", "Сигма базового размытия USM", "Sigma-Wert der USM-Unschärfe"),
    "锐化量（1=轻微，2=中等，3+=强锐化）": ("シャープ量(1=弱, 2=中, 3+=強)", "Quantité de netteté (1=léger, 2=moyen, 3+=fort)", "Степень резкости (1=слабо, 2=средне, 3+=сильно)", "Schärfungsmenge (1=leicht, 2=mittel, 3+=stark)"),
    "法线凹凸强度": ("ノーマルの凹凸強度", "Intensité du relief de la normale", "Сила рельефа нормали", "Normalen-Reliefstärke"),
    "反转法线Y方向（切换凹凸方向感知）": ("ノーマルのY方向を反転(凹凸の向きを切替)", "Inverser l'axe Y de la normale (inverse la perception du relief)", "Инвертировать ось Y нормали (смена восприятия рельефа)", "Y-Richtung der Normale invertieren (Reliefwahrnehmung umkehren)"),
    "无缝化算法": ("シームレスアルゴリズム", "Algorithme sans couture", "Алгоритм бесшовности", "Nahtlos-Algorithmus"),
    "边缘混合带占短边的比例": ("短辺に対するエッジ混合帯の比率", "Ratio de la zone de mélange par rapport au petit côté", "Доля зоны смешивания краёв от короткой стороны", "Verhältnis der Kantenmischzone zur kurzen Seite"),
    "拼接重叠区域占图像的比例": ("画像に対する重なり領域の比率", "Ratio de la zone de recouvrement par rapport à l'image", "Доля области перекрытия от изображения", "Verhältnis des Überlappungsbereichs zum Bild"),
    "边缘结构保护强度（越大越保护边缘）": ("エッジ構造保護強度(大きいほど保護)", "Intensité de protection des structures de bord (élevé=plus de protection)", "Сила защиты структуры краёв (больше=сильнее)", "Schutzstärke der Kantenstruktur (höher=mehr Schutz)"),
    "控制随机采样点数量，越多越接近原图": ("ランダムサンプル点数を制御、多いほど元画像に近い", "Contrôle le nombre de points d'échantillonnage ; plus = plus proche de l'original", "Управляет числом случайных точек; больше — ближе к оригиналу", "Steuert die Anzahl der Abtastpunkte; mehr = näher am Original"),
    "先缩到 1/2 做晶格化再还原，大幅加速": ("1/2に縮小して結晶化後に復元、大幅高速化", "Réduit à 1/2 pour cristalliser puis restaure, bien plus rapide", "Уменьшить до 1/2, кристаллизовать и восстановить — намного быстрее", "Auf 1/2 verkleinern, kristallisieren, wiederherstellen — viel schneller"),
    "控制分离光影的尺度，值越大去除越粗的光影": ("光影分離のスケールを制御、大きいほど粗い光影を除去", "Contrôle l'échelle de séparation de l'éclairage ; élevé=enlève un éclairage plus grossier", "Управляет масштабом разделения освещения; больше=удаляет более грубый свет", "Steuert die Skala der Lichttrennung; höher=entfernt gröbere Beleuchtung"),
    "基础光影层的生成方式": ("基本光影レイヤーの生成方法", "Comment la couche d'éclairage de base est générée", "Способ создания базового слоя освещения", "Wie die Basis-Beleuchtungsebene erzeugt wird"),
    "基色层模糊强度（强模糊模式）": ("ベースカラー層のぼかし強度(強ぼかしモード)", "Intensité de flou de la couche de base (mode Flou intense)", "Сила размытия базового слоя (режим сильного размытия)", "Weichzeichnungsstärke der Basisebene (Starke-Unschärfe-Modus)"),
    "基色层替换的颜色分量": ("ベース層が置換する色成分", "Composantes couleur remplacées par la couche de base", "Какие цветовые компоненты заменяет базовый слой", "Welche Farbkomponenten die Basisebene ersetzt"),
    "用原始亮度替换结果亮度，避免暗部裁切损失": ("結果の輝度を元の輝度で置換し暗部のクリップ損失を回避", "Remplace la luminance du résultat par celle d'origine pour éviter l'écrêtage des ombres", "Заменить яркость результата исходной, чтобы избежать потери в тенях", "Ergebnishelligkeit durch Originalhelligkeit ersetzen, um Schattenbeschnitt zu vermeiden"),
    "转换后重新归一化法线向量至单位长度": ("変換後にノーマルベクトルを単位長に再正規化", "Re-normaliser les vecteurs normaux après conversion", "Перенормировать векторы нормалей после конвертации", "Normalenvektoren nach der Konvertierung neu normalisieren"),
    "采样半径 (相对图像尺寸)": ("サンプリング半径(画像サイズ比)", "Rayon d'échantillonnage (relatif à la taille de l'image)", "Радиус выборки (относительно размера)", "Abtastradius (relativ zur Bildgröße)"),
    "AO 强度倍数": ("AO強度倍率", "Multiplicateur d'intensité AO", "Множитель силы AO", "AO-Stärkenmultiplikator"),
    "半球采样方向数 (越大越精确越慢)": ("半球サンプリング方向数(多いほど高精度・低速)", "Nombre de directions d'échantillonnage hémisphérique (plus=meilleure qualité, plus lent)", "Число направлений выборки полусферы (больше=точнее, медленнее)", "Anzahl der Halbkugel-Abtastrichtungen (mehr=bessere Qualität, langsamer)"),
    "曲率计算半径 (像素)": ("曲率計算半径(ピクセル)", "Rayon de calcul de courbure (pixels)", "Радиус расчёта кривизны (пиксели)", "Krümmungsberechnungsradius (Pixel)"),
    "横向分割线数量": ("横分割線の数", "Nombre de lignes de division horizontales", "Число горизонтальных линий деления", "Anzahl horizontaler Teilungslinien"),
    "纵向分割线数量": ("縦分割線の数", "Nombre de lignes de division verticales", "Число вертикальных линий деления", "Anzahl vertikaler Teilungslinien"),
    "用于置入叠加的前景图像": ("重ね配置用の前景画像", "Image de premier plan pour le placement en superposition", "Изображение переднего плана для наложения", "Vordergrundbild für die Überlagerung"),
    "要置入的文字内容": ("配置するテキスト内容", "Contenu du texte à placer", "Текст для вставки", "Zu platzierender Textinhalt"),
    "自定义字体文件路径，留空使用默认字体": ("カスタムフォントファイルのパス、空欄で既定フォント", "Chemin de police personnalisé, vide pour la police par défaut", "Путь к шрифту, пусто = шрифт по умолчанию", "Benutzerdefinierter Schriftpfad, leer für Standardschrift"),
    "文字大小（像素）": ("文字サイズ(ピクセル)", "Taille de police (pixels)", "Размер шрифта (пиксели)", "Schriftgröße (Pixel)"),
    "文字颜色 (RGBA)": ("文字色 (RGBA)", "Couleur du texte (RGBA)", "Цвет текста (RGBA)", "Textfarbe (RGBA)"),
    "字符之间的额外间距（像素）": ("文字間の追加間隔(ピクセル)", "Espacement supplémentaire entre caractères (pixels)", "Доп. интервал между символами (пиксели)", "Zusätzlicher Zeichenabstand (Pixel)"),
    "文字倾斜角度（度）": ("文字の傾き角度(度)", "Angle d'italique du texte (degrés)", "Угол наклона текста (градусы)", "Kursivwinkel des Textes (Grad)"),
    "基于字高的出血比例，实际出血 = 系数 × 字号": ("字高基準の裁ち落とし比率、実際=係数×文字サイズ", "Ratio de fond perdu selon la hauteur ; réel = ratio × taille", "Доля вылета от высоты шрифта; факт = коэф. × размер", "Anschnittverhältnis relativ zur Schrifthöhe; tatsächlich = Verhältnis × Größe"),
    "在工具面板中展开色调调整分类": ("ツールパネルで色調補正分類を展開", "Déployer la catégorie Réglage des couleurs", "Развернуть категорию «Коррекция цвета»", "Kategorie Farbanpassung im Bedienfeld erweitern"),
    "在工具面板中展开滤镜效果分类": ("ツールパネルでフィルター効果分類を展開", "Déployer la catégorie Effets de filtre", "Развернуть категорию «Фильтры»", "Kategorie Filtereffekte im Bedienfeld erweitern"),
    "在工具面板中展开贴图处理分类": ("ツールパネルでテクスチャ処理分類を展開", "Déployer la catégorie Traitement de texture", "Развернуть категорию «Обработка текстур»", "Kategorie Texturverarbeitung im Bedienfeld erweitern"),
    "在工具面板中展开几何变形分类": ("ツールパネルでジオメトリ変形分類を展開", "Déployer la catégorie Déformation géométrique", "Развернуть категорию «Геометрическая деформация»", "Kategorie Geometrische Verzerrung im Bedienfeld erweitern"),
    "当在节点编辑器里，选中图像节点时，右键菜单会增加一个快速跳转并修改图像的按钮": ("ノードエディタで画像ノードを選択時、右クリックメニューに画像を開いて編集するショートカットを追加", "Lorsqu'un nœud d'image est sélectionné dans l'éditeur de nœuds, le menu contextuel affiche un raccourci pour ouvrir et éditer l'image", "При выборе узла изображения в редакторе узлов в контекстном меню появится кнопка быстрого перехода к правке", "Wenn im Node-Editor ein Bild-Node ausgewählt ist, zeigt das Kontextmenü eine Verknüpfung zum Öffnen und Bearbeiten des Bildes"),
    "高频细节保留强度 (0=仅大形, 1=全细节)": ("高周波ディテール保持強度(0=大形のみ, 1=全ディテール)", "Intensité de détails fins (0=formes seules, 1=tous détails)", "Сила сохранения мелких деталей (0=только формы, 1=все детали)", "Stärke der Hochfrequenzdetails (0=nur Formen, 1=alle Details)"),
    "OpenGL (Y+) ⇄ DirectX (Y-) 法线格式切换": ("OpenGL (Y+) ⇄ DirectX (Y-) ノーマル形式切替", "Bascule de format de normale OpenGL (Y+) ⇄ DirectX (Y-)", "Переключение формата нормалей OpenGL (Y+) ⇄ DirectX (Y-)", "Normalenformat OpenGL (Y+) ⇄ DirectX (Y-) umschalten"),
    "全部 (L+a+b)": ("全て (L+a+b)", "Tout (L+a+b)", "Всё (L+a+b)", "Alle (L+a+b)"),
    "仅色度 (a+b)": ("色度のみ (a+b)", "Chroma seul (a+b)", "Только цветность (a+b)", "Nur Chroma (a+b)"),
    "仅明度 (L)": ("明度のみ (L)", "Luma seul (L)", "Только яркость (L)", "Nur Luma (L)"),
    "DX→OpenGL (翻转G)": ("DX→OpenGL (G反転)", "DX→OpenGL (inverser G)", "DX→OpenGL (перевернуть G)", "DX→OpenGL (G umkehren)"),
    "2通→3通 (重建B)": ("2ch→3ch (B再構築)", "2c→3c (reconstruire B)", "2кан→3кан (восстановить B)", "2-Kanal→3-Kanal (B rekonstruieren)"),
    "3通→2通 (清除B)": ("3ch→2ch (B消去)", "3c→2c (effacer B)", "3кан→2кан (очистить B)", "3-Kanal→2-Kanal (B löschen)"),
    "线性→sRGB": ("リニア→sRGB", "Linéaire→sRGB", "Линейный→sRGB", "Linear→sRGB"),
    "sRGB→线性": ("sRGB→リニア", "sRGB→Linéaire", "sRGB→Линейный", "sRGB→Linear"),
    "黑底白点": ("黒地・白点", "Fond noir, points blancs", "Чёрный фон, белые точки", "Schwarzer Grund, weiße Punkte"),
    "白底黑点": ("白地・黒点", "Fond blanc, points noirs", "Белый фон, чёрные точки", "Weißer Grund, schwarze Punkte"),
    "彩底白点": ("カラー地・白点", "Fond couleur, points blancs", "Цветной фон, белые точки", "Farbiger Grund, weiße Punkte"),
    "彩底黑点": ("カラー地・黒点", "Fond couleur, points noirs", "Цветной фон, чёрные точки", "Farbiger Grund, schwarze Punkte"),
    "白底彩点": ("白地・カラー点", "Fond blanc, points couleur", "Белый фон, цветные точки", "Weißer Grund, farbige Punkte"),
    "黑底彩点": ("黒地・カラー点", "Fond noir, points couleur", "Чёрный фон, цветные точки", "Schwarzer Grund, farbige Punkte"),
    "透明底彩点": ("透明地・カラー点", "Fond transparent, points couleur", "Прозрачный фон, цветные точки", "Transparenter Grund, farbige Punkte"),
    "彩底透明点": ("カラー地・透明点", "Fond couleur, points transparents", "Цветной фон, прозрачные точки", "Farbiger Grund, transparente Punkte"),
    "基于积分图的快速盒式模糊": ("積分画像による高速ボックスぼかし", "Flou de boîte rapide via images intégrales", "Быстрое коробчатое размытие на интегральных изображениях", "Schneller Boxweichzeichner mittels Integralbildern"),
    "分离卷积高斯模糊，更平滑": ("分離畳み込みガウスぼかし、より滑らか", "Flou gaussien à convolution séparable, plus lisse", "Сепарабельное гауссово размытие, более гладкое", "Separierbarer Gauß-Weichzeichner, glatter"),
    "多次盒式叠加，逼近高斯且更快": ("ボックスを多重適用、ガウス近似で高速", "Plusieurs passes de boîte, approxime le gaussien et plus rapide", "Несколько проходов коробки, приближает Гаусс и быстрее", "Mehrere Box-Durchgänge, nähert Gauß an und schneller"),
    "多轮小半径迭代，柔光发光效果": ("小半径の多重反復、ソフトグロー効果", "Itérations de petit rayon, effet de lueur douce", "Многократные итерации малого радиуса, мягкое свечение", "Mehrere Iterationen mit kleinem Radius, weicher Glüheffekt"),
    "旋转至指定角度做水平模糊后旋回": ("指定角度に回転し水平ぼかし後に戻す", "Pivoter à l'angle, flou horizontal, puis repivoter", "Повернуть на угол, размыть по горизонтали, вернуть", "Auf Winkel drehen, horizontal weichzeichnen, zurückdrehen"),
    "重复边缘像素": ("端ピクセルを繰り返す", "Répéter les pixels de bord", "Повторять краевые пиксели", "Randpixel wiederholen"),
    "对侧像素循环填充": ("反対側のピクセルで循環", "Enrouler depuis le côté opposé", "Заполнять пикселями с противоположной стороны", "Pixel von der gegenüberliegenden Seite umbrechen"),
    "亮图填白暗图填均值": ("明るい画像は白、暗い画像は平均で埋める", "Images claires=blanc, images sombres=moyenne", "Светлые=белый, тёмные=среднее", "Helle Bilder weiß, dunkle Bilder Mittelwert"),
    "越界像素从另一侧绕回": ("範囲外ピクセルは反対側に回り込む", "Les pixels hors limites s'enroulent de l'autre côté", "Пиксели вне границ заворачиваются на другую сторону", "Pixel außerhalb umbrechen zur Gegenseite"),
    "越界像素变为透明": ("範囲外ピクセルは透明になる", "Les pixels hors limites deviennent transparents", "Пиксели вне границ становятся прозрачными", "Pixel außerhalb werden transparent"),
    "正态分布随机噪点": ("正規分布のランダムノイズ", "Bruit aléatoire à distribution normale", "Случайный шум с нормальным распределением", "Normalverteiltes Zufallsrauschen"),
    "随机黑白像素": ("ランダムな白黒ピクセル", "Pixels noirs et blancs aléatoires", "Случайные чёрно-белые пиксели", "Zufällige schwarz-weiße Pixel"),
    "线性渐变边缘混合，快速、保持尺寸": ("線形グラデーションのエッジ混合、高速・サイズ維持", "Mélange de bords en dégradé linéaire, rapide, préserve la taille", "Линейное смешивание краёв, быстро, сохраняет размер", "Lineare Gradient-Kantenmischung, schnell, größenerhaltend"),
    "Seam Carving + 双频融合，更自然但可能裁切": ("Seam Carving + 二周波融合、より自然だが裁切の可能性", "Seam Carving + fusion bi-fréquence, plus naturel mais peut rogner", "Seam Carving + двухчастотное слияние, естественнее, но может обрезать", "Seam Carving + Zweiband-Fusion, natürlicher, kann aber beschneiden"),
    "注入微噪声打破量化断层，为后续调色提供缓冲": ("微ノイズ注入で量子化断層を破壊、後段の調色に余裕", "Injecte un micro-bruit pour briser les bandes, marge pour l'étalonnage", "Внести микрошум для разрушения полос, буфер для дальнейшей коррекции", "Mikro-Rauschen einfügen, um Quantisierungsbänder zu brechen, Puffer für weitere Farbkorrektur"),
    "降位深时注入TPDF三角噪声，掩盖色阶断层": ("ビット深度低減時にTPDF三角ノイズを注入し階調断層を隠す", "Injecter un bruit triangulaire TPDF lors de la réduction de profondeur pour masquer les bandes", "Внести TPDF-шум при снижении глубины, чтобы скрыть полосы", "TPDF-Dreiecksrauschen bei Bittiefenreduktion einfügen, um Banding zu verdecken"),
    "整图平均色作为均匀基色": ("全体平均色を均一ベースに", "Couleur moyenne globale comme base uniforme", "Средний цвет всего изображения как равномерная основа", "Globale Durchschnittsfarbe als gleichmäßige Basis"),
    "大幅模糊保留宏观光影渐变（更快更自然）": ("大幅ぼかしでマクロな光影グラデを保持(高速・自然)", "Flou intense préservant le dégradé d'éclairage macro (plus rapide et naturel)", "Сильное размытие сохраняет макро-градиент света (быстрее и естественнее)", "Starke Unschärfe erhält Makro-Lichtverlauf (schneller und natürlicher)"),
    "手动指定基色": ("ベースカラーを手動指定", "Spécifier manuellement la couleur de base", "Задать базовый цвет вручную", "Grundfarbe manuell festlegen"),
    "明度+色度全部替换": ("明度+色度を全て置換", "Remplacer luminance et chrominance", "Заменить и яркость, и цветность", "Luminanz und Chrominanz ersetzen"),
    "替换色相/饱和度，保留原始明度分布": ("色相/彩度を置換し元の明度分布を保持", "Remplacer teinte/saturation, conserver la luminance d'origine", "Заменить тон/насыщенность, сохранить исходную яркость", "Farbton/Sättigung ersetzen, Original-Luminanz beibehalten"),
    "替换明度，保留原始色相/饱和度": ("明度を置換し元の色相/彩度を保持", "Remplacer la luminance, conserver teinte/saturation", "Заменить яркость, сохранить тон/насыщенность", "Luminanz ersetzen, Original-Farbton/Sättigung beibehalten"),
    "翻转G通道: DX→OpenGL 法线约定转换": ("Gチャンネル反転: DX→OpenGL ノーマル規約変換", "Inverser le canal G : conversion DX→OpenGL", "Перевернуть канал G: конвертация DX→OpenGL", "G-Kanal umkehren: DX→OpenGL-Normalenkonvention"),
    "从R/G通道数学重建缺失的B通道": ("R/Gチャンネルから欠損Bチャンネルを数学的に再構築", "Reconstruire mathématiquement le canal B depuis R/G", "Восстановить канал B из R/G математически", "B-Kanal mathematisch aus R/G rekonstruieren"),
    "清除B通道数据, 转为2通道格式": ("Bチャンネルを消去し2チャンネル形式に", "Effacer le canal B, convertir en format 2 canaux", "Очистить канал B, формат 2 канала", "B-Kanal löschen, in 2-Kanal-Format umwandeln"),
    "强制将线性数据转为sRGB (修复色彩空间标签错误)": ("線形データをsRGBに強制変換(色空間タグ修正)", "Forcer linéaire en sRGB (corrige l'étiquette d'espace colorimétrique)", "Принудительно линейный в sRGB (исправить тег цв. пространства)", "Lineare Daten zu sRGB erzwingen (Farbraum-Tag korrigieren)"),
    "强制将sRGB数据转为线性 (修复色彩空间标签错误)": ("sRGBデータをリニアに強制変換(色空間タグ修正)", "Forcer sRGB en linéaire (corrige l'étiquette d'espace colorimétrique)", "Принудительно sRGB в линейный (исправить тег цв. пространства)", "sRGB-Daten zu linear erzwingen (Farbraum-Tag korrigieren)"),
    "从灰度贴图计算": ("グレースケール高さマップから計算", "Calculer depuis une carte de hauteur en niveaux de gris", "Рассчитать из карты высот", "Aus Graustufen-Höhenkarte berechnen"),
    "从法线贴图计算": ("ノーマルマップから計算", "Calculer depuis une carte de normales", "Рассчитать из карты нормалей", "Aus Normalkarte berechnen"),
    "网点与底色的组合方式": ("ドットと地色の組合せ方", "Combinaison points et couleur de fond", "Сочетание точек и фона", "Kombination aus Punkten und Hintergrundfarbe"),
    "暗处大点": ("暗部で大きな点", "Points plus grands dans les zones sombres", "Крупнее точки в тёмных областях", "Größere Punkte in dunklen Bereichen"),
    "亮处大点": ("明部で大きな点", "Points plus grands dans les zones claires", "Крупнее точки в светлых областях", "Größere Punkte in hellen Bereichen"),
    "原图为底，暗处叠加白色网点": ("元画像を地に、暗部へ白ドット", "Image d'origine en fond, points blancs dans les zones sombres", "Оригинал как фон, белые точки в тёмных областях", "Original als Grund, weiße Punkte in dunklen Bereichen"),
    "原图为底，亮处叠加黑色网点": ("元画像を地に、明部へ黒ドット", "Image d'origine en fond, points noirs dans les zones claires", "Оригинал как фон, чёрные точки в светлых областях", "Original als Grund, schwarze Punkte in hellen Bereichen"),
    "白底上以原图色画点，暗处大点": ("白地に元画像色で点、暗部で大", "Fond blanc, points en couleur d'origine, plus grands dans les zones sombres", "Белый фон, точки цветом оригинала, крупнее в тёмных областях", "Weißer Grund, Punkte in Originalfarbe, größer in dunklen Bereichen"),
    "黑底上以原图色画点，亮处大点": ("黒地に元画像色で点、明部で大", "Fond noir, points en couleur d'origine, plus grands dans les zones claires", "Чёрный фон, точки цветом оригинала, крупнее в светлых областях", "Schwarzer Grund, Punkte in Originalfarbe, größer in hellen Bereichen"),
    "透明底上以原图色画点，暗处大点": ("透明地に元画像色で点、暗部で大", "Fond transparent, points en couleur d'origine, plus grands dans les zones sombres", "Прозрачный фон, точки цветом оригинала, крупнее в тёмных областях", "Transparenter Grund, Punkte in Originalfarbe, größer in dunklen Bereichen"),
    "原图为底，亮处挖透明孔": ("元画像を地に、明部に透明な穴", "Image d'origine en fond, trous transparents dans les zones claires", "Оригинал как фон, прозрачные отверстия в светлых областях", "Original als Grund, transparente Löcher in hellen Bereichen"),
    "alpha = max(R,G,B) 重建透明通道": ("alpha = max(R,G,B) で透明チャンネル再構築", "alpha = max(R,G,B) reconstruit la transparence", "alpha = max(R,G,B) восстановление прозрачности", "alpha = max(R,G,B) Transparenz rekonstruieren"),
    "Sobel 算子，无参数": ("Sobelオペレータ、パラメータなし", "Opérateur Sobel, sans paramètres", "Оператор Собеля, без параметров", "Sobel-Operator, keine Parameter"),
    "FFT Poisson 求解，无参数": ("FFTポアソン求解、パラメータなし", "Solveur de Poisson FFT, sans paramètres", "FFT-решатель Пуассона, без параметров", "FFT-Poisson-Löser, keine Parameter"),
    "打破已固化的量化边界": ("固化した量子化境界を破壊", "Briser les frontières de quantification figées", "Разрушить устоявшиеся границы квантования", "Verfestigte Quantisierungsgrenzen aufbrechen"),
    "注入TPDF噪声掩盖色阶": ("TPDFノイズを注入し階調を隠す", "Injecter du bruit TPDF pour masquer le banding", "Внести TPDF-шум для скрытия полос", "TPDF-Rauschen einfügen, um Banding zu verdecken"),
    "注：高级缝合可能裁切图像": ("注：高度なシームは画像を裁切る可能性", "Note : la couture avancée peut rogner l'image", "Прим.: продвинутый шов может обрезать изображение", "Hinweis: Erweiterte Naht kann das Bild beschneiden"),
    "贝塞尔扭曲: 拖拽控制点 | P填色 | F重置 | Enter应用 | Esc取消": ("メッシュ変形: 制御点をドラッグ | P=塗り | F=リセット | Enter=適用 | Esc=取消", "Déformation maillage : glisser points | P=remplir | F=réinit | Enter=appliquer | Esc=annuler", "Деформация сеткой: тянуть точки | P=заливка | F=сброс | Enter=применить | Esc=отмена", "Netzverzerrung: Punkte ziehen | P=Füllen | F=Reset | Enter=Anwenden | Esc=Abbrechen"),
    "贝塞尔扭曲: 【1. 布局】摆放网格 | L切换 | P填色 | F重置 | Enter应用 | Esc取消": ("メッシュ変形: 【1.配置】グリッド配置 | L=切替 | P=塗り | F=リセット | Enter=適用 | Esc=取消", "Déformation maillage : [1. Disposition] placer grille | L=mode | P=remplir | F=réinit | Enter=appliquer | Esc=annuler", "Деформация сеткой: [1. Раскладка] разместить сетку | L=режим | P=заливка | F=сброс | Enter=применить | Esc=отмена", "Netzverzerrung: [1. Layout] Gitter platzieren | L=Modus | P=Füllen | F=Reset | Enter=Anwenden | Esc=Abbrechen"),
    "贝塞尔扭曲: 【2. 变形】拖拽控制点 | L切换 | P填色 | F重置 | Enter应用 | Esc取消": ("メッシュ変形: 【2.変形】制御点をドラッグ | L=切替 | P=塗り | F=リセット | Enter=適用 | Esc=取消", "Déformation maillage : [2. Déformer] glisser points | L=mode | P=remplir | F=réinit | Enter=appliquer | Esc=annuler", "Деформация сеткой: [2. Деформация] тянуть точки | L=режим | P=заливка | F=сброс | Enter=применить | Esc=отмена", "Netzverzerrung: [2. Verformen] Punkte ziehen | L=Modus | P=Füllen | F=Reset | Enter=Anwenden | Esc=Abbrechen"),
    "自由裁切: 拖拽边角/旋转 | P填色 | F重置 | Enter应用 | Esc取消": ("自由切り抜き: 角をドラッグ/回転 | P=塗り | F=リセット | Enter=適用 | Esc=取消", "Recadrage libre : glisser coins/pivoter | P=remplir | F=réinit | Enter=appliquer | Esc=annuler", "Свободная обрезка: тянуть углы/поворот | P=заливка | F=сброс | Enter=применить | Esc=отмена", "Freies Zuschneiden: Ecken ziehen/drehen | P=Füllen | F=Reset | Enter=Anwenden | Esc=Abbrechen"),
    "透视形变: L切换模式 | P填色 | F重置 | Enter应用 | Esc取消": ("透視変形: L=モード切替 | P=塗り | F=リセット | Enter=適用 | Esc=取消", "Déformation perspective : L=mode | P=remplir | F=réinit | Enter=appliquer | Esc=annuler", "Перспективная деформация: L=режим | P=заливка | F=сброс | Enter=применить | Esc=отмена", "Perspektivverzerrung: L=Modus | P=Füllen | F=Reset | Enter=Anwenden | Esc=Abbrechen"),
    "置入图像: 拖拽移动 | 角点缩放 | 旋转 [Shift吸附] | Enter应用 | Esc取消": ("画像配置: ドラッグで移動 | 角でスケール | 回転 [Shift=スナップ] | Enter=適用 | Esc=取消", "Placer image : glisser pour déplacer | coin pour redimensionner | rotation [Shift=magnétisme] | Enter=appliquer | Esc=annuler", "Вставить изображение: тянуть для перемещения | угол для масштаба | поворот [Shift=привязка] | Enter=применить | Esc=отмена", "Bild platzieren: ziehen zum Bewegen | Ecke zum Skalieren | Drehen [Shift=Einrasten] | Enter=Anwenden | Esc=Abbrechen"),
    "置入文字: 拖拽移动 | 角点缩放 | 旋转 [Shift吸附] | Enter应用 | Esc取消": ("テキスト配置: ドラッグで移動 | 角でスケール | 回転 [Shift=スナップ] | Enter=適用 | Esc=取消", "Placer texte : glisser pour déplacer | coin pour redimensionner | rotation [Shift=magnétisme] | Enter=appliquer | Esc=annuler", "Вставить текст: тянуть для перемещения | угол для масштаба | поворот [Shift=привязка] | Enter=применить | Esc=отмена", "Text platzieren: ziehen zum Bewegen | Ecke zum Skalieren | Drehen [Shift=Einrasten] | Enter=Anwenden | Esc=Abbrechen"),
    "切分图像: 拖拽分割线 | Shift 吸附 | Enter 应用 | Esc 取消": ("画像分割: 分割線をドラッグ | Shift=スナップ | Enter=適用 | Esc=取消", "Découper image : glisser les lignes | Shift=magnétisme | Enter=appliquer | Esc=annuler", "Разрезать изображение: тянуть линии | Shift=привязка | Enter=применить | Esc=отмена", "Bild teilen: Linien ziehen | Shift=Einrasten | Enter=Anwenden | Esc=Abbrechen"),
    "贝塞尔扭曲另存": ("メッシュ変形を別名保存", "Déformation maillage - Enregistrer sous", "Деформация сеткой — сохранить как", "Netzverzerrung speichern unter"),
    "自由裁切另存": ("自由切り抜きを別名保存", "Recadrage libre - Enregistrer sous", "Свободная обрезка — сохранить как", "Freies Zuschneiden speichern unter"),
    "透视形变另存": ("透視変形を別名保存", "Déformation perspective - Enregistrer sous", "Перспективная деформация — сохранить как", "Perspektivverzerrung speichern unter"),
    "置入图像另存": ("画像配置を別名保存", "Placer image - Enregistrer sous", "Вставить изображение — сохранить как", "Bild platzieren speichern unter"),
    "置入文字另存": ("テキスト配置を別名保存", "Placer texte - Enregistrer sous", "Вставить текст — сохранить как", "Text platzieren speichern unter"),
    "进入{label}模态": ("{label}モードに入る", "Entrer en mode {label}", "Войти в режим {label}", "{label}-Modus aufrufen"),
    "矩阵求解失败": ("行列の求解に失敗", "Échec de résolution de la matrice", "Не удалось решить матрицу", "Matrixlösung fehlgeschlagen"),
    "裁切应用失败: {e}": ("切り抜きの適用に失敗: {e}", "Échec d'application du recadrage : {e}", "Не удалось применить обрезку: {e}", "Zuschnitt fehlgeschlagen: {e}"),
    "应用失败: {e}": ("適用に失敗: {e}", "Échec de l'application : {e}", "Не удалось применить: {e}", "Anwendung fehlgeschlagen: {e}"),
    "(双击切换)": ("(ダブルクリックで切替)", "(double-clic pour changer)", "(двойной клик для смены)", "(Doppelklick zum Wechseln)"),
    "{mode}(双击切换)": ("{mode}(ダブルクリックで切替)", "{mode} (double-clic pour changer)", "{mode} (двойной клик)", "{mode} (Doppelklick zum Wechseln)"),
    "【1. 布局】定义平面": ("【1.配置】平面を定義", "[1. Disposition] Définir le plan", "[1. Раскладка] задать плоскость", "[1. Layout] Ebene festlegen"),
    "【2. 变形】拖拽图钉": ("【2.変形】ピンをドラッグ", "[2. Déformer] glisser les épingles", "[2. Деформация] тянуть булавки", "[2. Verformen] Pins ziehen"),
    "【1. 布局】摆放网格": ("【1.配置】グリッド配置", "[1. Disposition] Placer la grille", "[1. Раскладка] разместить сетку", "[1. Layout] Gitter platzieren"),
    "【2. 变形】拖拽控制点": ("【2.変形】制御点をドラッグ", "[2. Déformer] glisser les points", "[2. Деформация] тянуть точки", "[2. Verformen] Punkte ziehen"),
    "warp:贝塞尔扭曲": ("warp:メッシュ変形", "warp:Déformation maillage", "warp:Деформация сеткой", "warp:Netzverzerrung"),
    "warp:自由裁切": ("warp:自由切り抜き", "warp:Recadrage libre", "warp:Свободная обрезка", "warp:Freies Zuschneiden"),
    "warp:透视形变": ("warp:透視変形", "warp:Déformation perspective", "warp:Перспективная деформация", "warp:Perspektivverzerrung"),
    "warp:置入图像": ("warp:画像配置", "warp:Placer image", "warp:Вставить изображение", "warp:Bild platzieren"),
    "warp:置入文字": ("warp:テキスト配置", "warp:Placer texte", "warp:Вставить текст", "warp:Text platzieren"),
    "warp:切分图像": ("warp:画像分割", "warp:Découper image", "warp:Разрезать изображение", "warp:Bild teilen"),
    "[图像编辑工具集]": ("[画像エディタツール]", "[Outils d'édition d'image]", "[Инструменты редактора изображений]", "[Bildbearbeitungswerkzeuge]"),
    "[贝塞尔扭曲]": ("[メッシュ変形]", "[Déformation maillage]", "[Деформация сеткой]", "[Netzverzerrung]"),
    "[自由裁切]": ("[自由切り抜き]", "[Recadrage libre]", "[Свободная обрезка]", "[Freies Zuschneiden]"),
    "[透视形变]": ("[透視変形]", "[Déformation perspective]", "[Перспективная деформация]", "[Perspektivverzerrung]"),
    "[置入图像]": ("[画像配置]", "[Placer image]", "[Вставить изображение]", "[Bild platzieren]"),
    "[置入文字]": ("[テキスト配置]", "[Placer texte]", "[Вставить текст]", "[Text platzieren]"),
    "[切分图像]": ("[画像分割]", "[Découper image]", "[Разрезать изображение]", "[Bild teilen]"),
    "网格变形 (GPU烘焙) | 拖拽控制点 | 填充: {pad} [P切换] | F 重置 | Enter 应用 | Esc 取消": ("メッシュ変形 (GPU) | 制御点をドラッグ | 塗り: {pad} [P] | F=リセット | Enter=適用 | Esc=取消", "Déformation maillage (GPU) | glisser points | Remplir: {pad} [P] | F=réinit | Enter=appliquer | Esc=annuler", "Деформация сеткой (GPU) | тянуть точки | Заливка: {pad} [P] | F=сброс | Enter=применить | Esc=отмена", "Netzverzerrung (GPU) | Punkte ziehen | Füllen: {pad} [P] | F=Reset | Enter=Anwenden | Esc=Abbrechen"),
    "{mode} | 填充: {pad} [P切换] | L 切换模式 | F 重置 | Enter 应用 | Esc 取消": ("{mode} | 塗り: {pad} [P] | L=モード | F=リセット | Enter=適用 | Esc=取消", "{mode} | Remplir: {pad} [P] | L=mode | F=réinit | Enter=appliquer | Esc=annuler", "{mode} | Заливка: {pad} [P] | L=режим | F=сброс | Enter=применить | Esc=отмена", "{mode} | Füllen: {pad} [P] | L=Modus | F=Reset | Enter=Anwenden | Esc=Abbrechen"),
    "自由裁切 | 拖拽边缘 | 旋转 ({angle}°) [Shift吸附] | 填充: {mode} [按P切换] | F填满 | Enter应用 | Esc取消": ("自由切り抜き | 縁をドラッグ | 回転 ({angle}°) [Shift=スナップ] | 塗り: {mode} [P] | F=フィット | Enter=適用 | Esc=取消", "Recadrage libre | glisser bords | rotation ({angle}°) [Shift=magnétisme] | Remplir: {mode} [P] | F=remplir | Enter=appliquer | Esc=annuler", "Свободная обрезка | тянуть края | поворот ({angle}°) [Shift=привязка] | Заливка: {mode} [P] | F=заполнить | Enter=применить | Esc=отмена", "Freies Zuschneiden | Ränder ziehen | Drehen ({angle}°) [Shift=Einrasten] | Füllen: {mode} [P] | F=Füllen | Enter=Anwenden | Esc=Abbrechen"),
    "置入图像 | 拖拽移动 | 角点缩放 | 旋转 ({angle}°) [Shift吸附] | Enter应用 | Esc取消": ("画像配置 | ドラッグで移動 | 角でスケール | 回転 ({angle}°) [Shift=スナップ] | Enter=適用 | Esc=取消", "Placer image | glisser pour déplacer | coin pour redimensionner | rotation ({angle}°) [Shift=magnétisme] | Enter=appliquer | Esc=annuler", "Вставить изображение | тянуть для перемещения | угол для масштаба | поворот ({angle}°) [Shift=привязка] | Enter=применить | Esc=отмена", "Bild platzieren | ziehen zum Bewegen | Ecke zum Skalieren | Drehen ({angle}°) [Shift=Einrasten] | Enter=Anwenden | Esc=Abbrechen"),
    "置入文字 | 拖拽移动 | 角点缩放 | 旋转 ({angle}°) [Shift吸附] | Enter应用 | Esc取消": ("テキスト配置 | ドラッグで移動 | 角でスケール | 回転 ({angle}°) [Shift=スナップ] | Enter=適用 | Esc=取消", "Placer texte | glisser pour déplacer | coin pour redimensionner | rotation ({angle}°) [Shift=magnétisme] | Enter=appliquer | Esc=annuler", "Вставить текст | тянуть для перемещения | угол для масштаба | поворот ({angle}°) [Shift=привязка] | Enter=применить | Esc=отмена", "Text platzieren | ziehen zum Bewegen | Ecke zum Skalieren | Drehen ({angle}°) [Shift=Einrasten] | Enter=Anwenden | Esc=Abbrechen"),
    "切分图像 | 拖拽分割线 | Shift 吸附 | 纵:{cols} 横:{rows} | Enter 应用 | Esc 取消": ("画像分割 | 分割線をドラッグ | Shift=スナップ | 縦:{cols} 横:{rows} | Enter=適用 | Esc=取消", "Découper image | glisser lignes | Shift=magnétisme | Col:{cols} Lig:{rows} | Enter=appliquer | Esc=annuler", "Разрезать изображение | тянуть линии | Shift=привязка | Стлб:{cols} Стр:{rows} | Enter=применить | Esc=отмена", "Bild teilen | Linien ziehen | Shift=Einrasten | Sp:{cols} Z:{rows} | Enter=Anwenden | Esc=Abbrechen"),
    "填充: {pad} [P切换]": ("塗り: {pad} [P切替]", "Remplir : {pad} [P]", "Заливка: {pad} [P]", "Füllen: {pad} [P]"),
    "GPU 模糊算法": ("GPUぼかしアルゴリズム", "Algorithme de flou GPU", "Алгоритм размытия GPU", "GPU-Weichzeichnungsalgorithmus"),
    "GPU 着色器(快) 或 CPU numpy": ("GPUシェーダー(高速) または CPU numpy", "Shader GPU (rapide) ou CPU numpy", "Шейдер GPU (быстро) или CPU numpy", "GPU-Shader (schnell) oder CPU-numpy"),
    "GPU 着色器(快、半径无关) 或 CPU numpy": ("GPUシェーダー(高速・半径非依存) または CPU numpy", "Shader GPU (rapide, indépendant du rayon) ou CPU numpy", "Шейдер GPU (быстро, не зависит от радиуса) или CPU numpy", "GPU-Shader (schnell, radiusunabhängig) oder CPU-numpy"),
    "按图像对角线比例 (0-100)，预览/应用一致": ("画像対角線の比率 (0-100)、プレビュー/適用で一致", "Ratio de la diagonale de l'image (0-100), cohérent aperçu/application", "Доля диагонали изображения (0-100), одинаково в предпросмотре/применении", "Verhältnis der Bilddiagonale (0-100), konsistent für Vorschau/Anwendung"),
    "方向模糊角度 (-180~180, 0=水平)": ("方向ぼかしの角度 (-180~180, 0=水平)", "Angle du flou directionnel (-180~180, 0=horizontal)", "Угол направленного размытия (-180~180, 0=горизонталь)", "Winkel der Richtungsunschärfe (-180~180, 0=horizontal)"),
    "图像边缘外像素的填充方式（所有 GPU 模式生效）": ("画像端外ピクセルの埋め方(全GPUモードで有効)", "Remplissage hors limites (s'applique à tous les modes GPU)", "Заполнение пикселей вне границ (для всех режимов GPU)", "Füllmodus außerhalb des Bildes (gilt für alle GPU-Modi)"),
    "曲率尺度(像素)：求导前对高度预模糊的半径，越大越保留宏观曲率、抹去细节": ("曲率スケール(ピクセル):微分前に高さをぼかす半径、大きいほどマクロ曲率を保持し細部を除去", "Échelle de courbure (pixels) : rayon de pré-flou avant la dérivée ; plus grand=conserve la courbure macro, supprime les détails", "Масштаб кривизны (пиксели): радиус предразмытия высоты перед производной; больше=макро-кривизна, меньше деталей", "Krümmungsskala (Pixel): Vorweichzeichnungsradius vor der Ableitung; größer=erhält Makrokrümmung, entfernt Details"),
    "[USM锐化]": ("[USMシャープ]", "[Netteté USM]", "[Нерезкая маска]", "[USM-Schärfen]"),
    "[减少杂色]": ("[ノイズ除去]", "[Réduction du bruit]", "[Шумоподавление]", "[Entrauschen]"),
    "[均匀光影]": ("[均一ライティング]", "[Éclairage uniforme]", "[Равномерный свет]", "[Gleichmäßige Beleuchtung]"),
    "[晶格化]": ("[結晶化]", "[Cristalliser]", "[Кристаллизация]", "[Kristallisieren]"),
    "[曲率图]": ("[曲率]", "[Courbure]", "[Кривизна]", "[Krümmung]"),
    "[模糊]": ("[ぼかし]", "[Flou]", "[Размытие]", "[Weichzeichnen]"),
    "[法线生成]": ("[ノーマル生成]", "[Normale]", "[Карта нормалей]", "[Normale]"),
    "[高反差保留]": ("[ハイパス]", "[Passe-haut]", "[Цветовой контраст]", "[Hochpass]"),
    "[高度→AO]": ("[高さ→AO]", "[Hauteur→AO]", "[Высота→AO]", "[Höhe→AO]"),
}
M.update(M2)

LANGS = [("ja_JP", 0), ("fr_FR", 1), ("ru_RU", 2), ("de_DE", 3)]
HEADER = "# 自动生成 (scripts/gen_lang_packs.py)。未覆盖键回退英文。\n\ndata = {\n"

for code, idx in LANGS:
    lines = [HEADER]
    for zh, en in EN.items():
        val = M[zh][idx] if zh in M else en
        kj = json.dumps(zh, ensure_ascii=False)
        vj = json.dumps(val, ensure_ascii=False)
        lines.append(f"    {kj}: {vj},\n")
    lines.append("}\n")
    out = os.path.join(TRANS_DIR, f"{code}.py")
    with open(out, "w", encoding="utf-8") as f:
        f.write("".join(lines))
    translated = sum(1 for zh in EN if zh in M)
    print(f"{code}.py: {len(EN)} keys ({translated} translated, {len(EN)-translated} EN fallback)")

print("done")
